name: Push TF at any branch/CI

on:
  pull_request:
    branches:
      - master
      - test
    paths:
      - '**.tf'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: 'NPM CI'
        run: |
          npm ci
          npm run build --if-present
          npm test
        env:
          CI: true
      - name: Initialize Google Cloud SDK
        uses: zxyle/publish-gae-action@master
        with:
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.PROJECT_ID }}
      - name: Creating client-secrets.json
        run: gcloud auth activate-service-account ${{ secrets.GCP_SA_EMAIL }} --key-file=client-secret.json

      - name: 'Terraform Init'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.21
          tf_actions_subcommand: 'init'
          tf_actions_working_dir: terraform
          tf_actions_comment: true
          args: '-backend-config=envs/test/backend.tf'
        env:
          GOOGLE_APPLICATION_CREDENTIALS: './client-secret.json'
      - name: 'Terraform Plan'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.21
          tf_actions_subcommand: 'plan'
          tf_actions_working_dir: terraform
          tf_actions_comment: true
          args: '-var-file=envs/test/test.tfvars'
        env:
          GOOGLE_APPLICATION_CREDENTIALS: './client-secret.json'
